# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TutorialGoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TutorialGoogleMap
    pod 'GoogleMaps'
    pod 'GooglePlaces' 
    pod 'SwiftyJSON'
    pod 'Alamofire'
 end
